name: Test

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.34.0]

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Verify formatting
        run: make fmt-check

      - name: Run tests
        run: make test
