name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.44.0

      - name: Verify formatting & other checks
        run: make check

  test:
    needs: setup
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: make test

  react_native_ci_job:
    needs: setup
    runs-on: ubuntu-latest
    name: React Native Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: React Native CI
        uses: aslamanver/react-native-docker@v1
      - name: Install NPM Dependencies
        run: npm install
      - name: Run NX Dev Android Build
        run: npx nx build-android mobile
